
-- We need to rewrite ONLY the TODO Upload ECC Doc - Cert Eligible.
-- If the first reviewer rejects it, that is an SBM_SUBMITTAL_ATTRDTL (and I believe an update to the WKF_INSTANCE). The CEN_CUST_TX is not updated at all unless the second reviewer gets to it (Keep in mind these do not share a true link)
-- The logic needs to show the link under any scenario where they have not achieved a valid approved submittal, and one is not currently in either valid pending state (reviewer 1 or 2 is looking at it)




SELECT * FROM SBM_SUBMITTAL WHERE SUBMITTAL_ID='133969'
SUBMITTAL_SERNO	WKF_SERNO	SUBMITTAL_ID	COLLECTION_ID	SUBCOLLECTION_CD	TOPIC	SHORT_TITLE_1	SHORT_TITLE_2	DESCR	PRIMARY_CUST_ID	CLONEFROM_SUBMITTAL_SERNO	CREATE_DT	CREATE_BY	LAST_CHANGE_DT	LAST_CHANGE_BY	ASSIGNED_PROP_ID	DESCR_WITHOUT_HTML	PARENT_CUST_ID	PARENT_SUBMITTAL_SERNO
133969	139771	133969	AT_EXAM_ECC_APP	ATHLETIC_TRAINER	APPLICATION	-	-	-	BOC389067	-	08/18/2021	BOCSELFSERVICE	08/18/2021	BOCSELFSERVICE	-	-	BOC389067	-


SELECT * FROM WKF_INSTANCE WHERE WKF_SERNO='139771'
WKF_SERNO	WORKFLOW	PARENT_WKF_SERNO	CURRENT_STATE_CD	SOURCE	CREATE_DT	CREATE_BY	LAST_CHANGE_DT	LAST_CHANGE_BY
139771	AT_ECC_APP	-	REJECTED	SBMSSAMYSUBMITTALS	08/18/2021	BOCSELFSERVICE	09/20/2021	ALLENH


SELECT * FROM CEN_CUST_TX tx WHERE tx.cust_id= 'BOC389067' AND tx.category_cd = 'ECC' AND tx.end_dt > SYSDATE
TX_SERNO	CUST_ID	CATEGORY_CD	LEVEL1	LEVEL2	LEVEL3	LEVEL4	LEVEL5	START_DT	END_DT	STATUS_CD	CREDIT_PTS_REQUESTED	CREDIT_PTS_ALLOWED	CREDIT_PTS_APPROVED	CREDIT_UNIT	CREATE_DT	CREATE_BY	LAST_CHANGE_DT	LAST_CHANGE_BY	ACTIVE_FL	RESULT_CD	RESULT_SCORE	TARGET_SCORE
128024	BOC389067	ECC	NSC	NSC_BLS	-	-	-	03/15/2021	03/15/2023	REVIEW	1	1	0	-	08/18/2021	BOCSELFSERVICE	08/18/2021	BOCSELFSERVICE	Y	-	-	-