SELECT *
FROM CEN_CUST_TX cct
  LEFT JOIN CEN_CUST_TX_ATTRDTL ccta ON ccta.tx_serno=cct.tx_serno
WHERE CATEGORY_CD IN ('ECC');


ATTRIBUTE_TY


'AT_MAINTAIN_DISSERTATION',
'AT_EXAM_ECC_UPLOAD',
'AT_MAINTAIN_CEUS',
'AT_MAINTAIN_INSTITUTION',
'AT_MAINTAIN_PROVIDER_NUMBER',
'AT_EXAM_ECC_ID',
'AT_MAINTAIN_RESIDENCY_FOCUS',
'AT_EXAM_ECC_UPLOAD1',
'AT_MAINTAIN_PUBLICATION',
'AT_MAINTAIN_COURSE_TITLE',
'AT_MAINTAIN_NON_BOC_PROVIDER',
'AT_MAINTAIN_PROGRAM',
'AT_MAINTAIN_ARTICLE',
'AT_MAINTAIN_BOC_PROVIDER',
'AT_MAINTAIN_CREDIT_HOURS',
'AT_MAINTAIN_YEARS',


SELECT * FROM CEN_CUST_TX cct WHERE CATEGORY_CD IN ('CAT_A', 'CAT B', 'CAT_C', 'CAT_D', 'EBP', 'ECC', 'CAT_A_FIRST', 'CAT_B_FIRST', 'CAT_C_FIRST', 'CAT_D_FIRST', 'ECC_FIRST') AND CREATE_DT >= '01/01/2022' AND CREATE_DT <= '12/31/2023';

https://cert.bocatc.org/bocssa/f?p=BOCSSA:2529:10387842566003::::

P0_SUBMITTAL_SERNO,G_WKF_FL,G_WKF_SERNO,G_WKF_TRANS_VERB,G_CUST_ID:
425159,Y,569852,CEUSUMMARY,090402137

"TX_CONTEXT_QUAL" <- Tied activity to ce form

SELECT * FROM CRT_CUST_PERIOD WHERE CUST_ID='000010271' AND => START_DATE of 1/1/2022