SELECT
  AHR_VW_CUSTOMER.CUST_ID,
  AHR_VW_CUSTOMER.FIRST_NM,
  AHR_VW_CUSTOMER.LAST_NM,
  WKFCFGLIB.getcurrentstatedescr(SBM_SUBMITTAL.WKF_SERNO),
  SBM_SUBMITTAL.LAST_CHANGE_DT,
  DT_SBM_SUBMITTAL_ATTRDTL_01.DVAR,
  WKF_TRANSITION_LOG.LOG_TIMESTAMP AS SUBMITTED_DATE
FROM
  AHR_VW_CUSTOMER
  INNER JOIN SBM_SUBMITTAL ON (
    SBM_SUBMITTAL.PRIMARY_CUST_ID = AHR_VW_CUSTOMER.CUST_ID
  )
  INNER JOIN WKF_TRANSITION_LOG ON WKF_TRANSITION_LOG.WKF_SERNO=SBM_SUBMITTAL.WKF_SERNO
  INNER JOIN (
    select
      SBM_SUBMIT1.SUBMITTAL_SERNO,
      SBM_SUBMIT_ATTR1.ATTRIBUTE_TY,
      SBM_SUBMIT_ATTR1.SHORT_NAME,
      SBM_SUBMIT_ATTR1.DESCR TYPE_DESCR,
      SBM_SUBMIT_ATTR1.FILE_ENABLE,
      NULL FILE_SERNO,
      NULL IS_FILE_ATTACHED,
      NULL ATTRIBUTE_CD,
      NULL CODE_DESCR,
      NULL CVAR,
      NULL DVAR,
      NULL NVAR,
      'Y' OUTER_JOIN
    from
      STD_CFG_ATTRTYPE SBM_SUBMIT_ATTR1,
      SBM_SUBMITTAL SBM_SUBMIT1
    where
      nvl(SBM_SUBMIT_ATTR1.DIMENSION_ENABLE, 'N') = 'N'
      and not exists (
        select
          'X'
        from
          SBM_SUBMITTAL_ATTRDTL SBM_SUBMIT_ATTRDTL1
        where
          SBM_SUBMIT1.submittal_serno = SBM_SUBMIT_ATTRDTL1.submittal_serno
          and SBM_SUBMIT_ATTRDTL1.ATTRIBUTE_TY = SBM_SUBMIT_ATTR1.ATTRIBUTE_TY
      )
      and SBM_SUBMIT_ATTR1.attribute_ty in (
        select
          SBM_SUBMIT_T1.attribute_ty
        from
          std_cfg_attrpage_types SBM_SUBMIT_T1,
          std_cfg_attrpage_mapping SBM_SUBMIT_M1
        where
          SBM_SUBMIT_T1.attrpage_serno = SBM_SUBMIT_M1.attrpage_serno
          and SBM_SUBMIT_M1.package_nm in (
            'SBMSSAMYSUBMITTALS',
            'SBMSSAMYSUBMITTALATTRDTL'
          )
      )
    union
    all
    select
      SBM_SUBMIT_ATTRDTL2.submittal_serno,
      SBM_SUBMIT_ATTRDTL2.ATTRIBUTE_TY,
      SBM_SUBMIT_ATTR2.SHORT_NAME,
      SBM_SUBMIT_ATTR2.DESCR TYPE_DESCR,
      SBM_SUBMIT_ATTR2.FILE_ENABLE,
      SBM_SUBMIT_ATTRDTL2.FILE_SERNO,
      Case
        when SBM_SUBMIT_ATTRDTL2.FILE_SERNO IS NULL Then 'NO'
        Else 'YES'
      end IS_FILE_ATTACHED,
      SBM_SUBMIT_ATTRDTL2.ATTRIBUTE_CD,
      SBM_SUBMIT_ATTRCD1.DESCR CODE_DESCR,
      SBM_SUBMIT_ATTRDTL2.CVAR,
      SBM_SUBMIT_ATTRDTL2.DVAR,
      SBM_SUBMIT_ATTRDTL2.NVAR,
      'N' OUTER_JOIN
    from
      SBM_SUBMITTAL_ATTRDTL SBM_SUBMIT_ATTRDTL2,
      STD_CFG_ATTRCODE SBM_SUBMIT_ATTRCD1,
      STD_CFG_ATTRTYPE SBM_SUBMIT_ATTR2
    where
      nvl(SBM_SUBMIT_ATTR2.DIMENSION_ENABLE, 'N') = 'N'
      and SBM_SUBMIT_ATTRCD1.ATTRIBUTE_TY = SBM_SUBMIT_ATTR2.ATTRIBUTE_TY
      and SBM_SUBMIT_ATTRDTL2.ATTRIBUTE_TY = SBM_SUBMIT_ATTRCD1.ATTRIBUTE_TY
      and SBM_SUBMIT_ATTRDTL2.ATTRIBUTE_CD = SBM_SUBMIT_ATTRCD1.ATTRIBUTE_CD
  ) DT_SBM_SUBMITTAL_ATTRDTL_01 ON (
    DT_SBM_SUBMITTAL_ATTRDTL_01.SUBMITTAL_SERNO = SBM_SUBMITTAL.SUBMITTAL_SERNO
  )
WHERE
  (
    AHR_VW_CUSTOMER.CUST_TY IN ('I')
    AND SBM_SUBMITTAL.COLLECTION_ID IN ('AT_MAINTAIN_APP')
    AND WKF_TRANSITION_LOG.STATE_STATE_CD='PENDING'
    AND WKF_TRANSITION_LOG.END_STATE_CD='COMPLETE'
    AND WKFCFGLIB.GetCurrentState(SBM_SUBMITTAL.WKF_SERNO) IN (
      'COMPLETE',
      'COMPLETE_AUDIT_SELECTED',
      'COMPLIANT'
    )
    AND DT_SBM_SUBMITTAL_ATTRDTL_01.ATTRIBUTE_TY IN ('COMPLETE_DATE')
  )